### ISSUE TITLE
Comments on initial notebook

### ISSUE THREAD

**Issue by mgelbart** [UBC-CS/lipo-python#3]
Comments on [initial notebook](https://github.com/UBC-CS/lipo-python/blob/42cf7fb6162580224324cea2038dc99eac09b6d1/docs/LIPO-implementation.ipynb):

- variable names
  - `values` and `evals` is confusing. How about `X` and `y`?
  - `upper_bound` should be `lower bound`?
- refactor is that we pass in bounds, not grid, to `LIPO`
  - use [np.random.uniform](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.random.uniform.html)

```
x = np.random.uniform(d)
proposal = x * (bound_maxs - bound_mins) + bound_mins
```

- start making a library of visualizations
  - loss vs. iterations (either showing all lines or take mean/median with error bars for the different runs)
  - loss vs. wall time (can do later)
  - density plots of solutions for 1d or 2d (across runs)

- move out of Jupyter
- start thinking about adaptive version

**Comment by bradleypick** [comment]
All addressed in the last 10 days
